-- Tabela: Cennik
CREATE TABLE Cennik (
    id_uslugi NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa_uslugi VARCHAR2(100) NOT NULL,
    cena_bazowa NUMBER(10, 2) NOT NULL,
    cena_za_kg NUMBER(10, 2)
);

-- Tabela: Faktury
CREATE TABLE Faktury (
    id_faktury NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numer_faktury VARCHAR2(50) NOT NULL UNIQUE,
    id_klienta NUMBER NOT NULL, -- Powiązanie z SQLSRV-HQ
    id_przesylki NUMBER,        -- Powiązanie z SQLSRV-HQ (przesyłka)
    kwota_netto NUMBER(10, 2) NOT NULL,
    kwota_vat NUMBER(10, 2) NOT NULL,
    kwota_brutto NUMBER(10, 2) NOT NULL,
    data_wystawienia DATE DEFAULT SYSDATE
);

-- Tabela: Platnosci
CREATE TABLE Platnosci (
    id_platnosci NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_faktury NUMBER NOT NULL,
    kwota NUMBER(10, 2) NOT NULL,
    data_platnosci DATE DEFAULT SYSDATE,
    metoda_platnosci VARCHAR2(30),
    CONSTRAINT fk_platnosc_faktura FOREIGN KEY (id_faktury) REFERENCES Faktury(id_faktury)
);

-- Tabela: RozliczeniaKurierskie
CREATE TABLE RozliczeniaKurierskie (
    id_rozliczenia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_kuriera NUMBER NOT NULL, -- Powiązanie z SQLSRV-HQ
    okres_rozliczeniowy VARCHAR2(7) NOT NULL,
    kwota_prowizji NUMBER(10, 2) NOT NULL,
    status_rozliczenia VARCHAR2(20) DEFAULT 'DO_RAPORTU'
);
