-- Czyszczenie istniejących tabel
DECLARE
  PROCEDURE safe_drop_table(p_table IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ' || p_table || ' CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;
BEGIN
  safe_drop_table('Platnosci');
  safe_drop_table('Faktury');
  safe_drop_table('Cennik');
  safe_drop_table('RozliczeniaKurierskie');
END;
/

-- Tabela: Cennik
CREATE TABLE Cennik (
    id_uslugi NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa_uslugi VARCHAR2(100) NOT NULL,
    cena_bazowa NUMBER(10, 2) NOT NULL,
    cena_za_kg NUMBER(10, 2)
);

-- Tabela: Faktury
CREATE TABLE Faktury (
    id_faktury NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numer_faktury VARCHAR2(50) NOT NULL UNIQUE,
    id_klienta NUMBER NOT NULL, -- Powiązanie z HQ
    id_przesylki NUMBER,        -- Powiązanie z HQ
    kwota_netto NUMBER(10, 2) NOT NULL,
    kwota_vat NUMBER(10, 2) NOT NULL,
    kwota_brutto NUMBER(10, 2) NOT NULL,
    data_wystawienia DATE DEFAULT SYSDATE
);

-- Tabela: Platnosci
CREATE TABLE Platnosci (
    id_platnosci NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_faktury NUMBER NOT NULL,
    kwota NUMBER(10, 2) NOT NULL,
    data_platnosci DATE DEFAULT SYSDATE,
    metoda_platnosci VARCHAR2(30),
    CONSTRAINT fk_platnosc_faktura FOREIGN KEY (id_faktury) REFERENCES Faktury(id_faktury)
);

-- Tabela: RozliczeniaKurierskie
CREATE TABLE RozliczeniaKurierskie (
    id_rozliczenia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_kuriera NUMBER NOT NULL, -- Powiązanie z HQ
    okres_rozliczeniowy VARCHAR2(7) NOT NULL,
    kwota_prowizji NUMBER(10, 2) NOT NULL,
    status_rozliczenia VARCHAR2(20) DEFAULT 'DO_RAPORTU'
);
