-- Oracle Cennik
-- 1. Tworzenie Ról
CREATE ROLE role_admin;
CREATE ROLE role_app;
CREATE ROLE role_ro;
CREATE ROLE role_rep;
CREATE ROLE role_audit;

-- 2. Tworzenie Użytkowników
CREATE USER COURIER_ADMIN IDENTIFIED BY AdminSecure123!;
CREATE USER COURIER_APP IDENTIFIED BY AppSecure123!;
CREATE USER COURIER_RO IDENTIFIED BY ROSecure123!;
CREATE USER COURIER_REP IDENTIFIED BY RepSecure123!;
CREATE USER COURIER_AUDIT IDENTIFIED BY AuditSecure123!;

-- Podstawowe uprawnienia do logowania
GRANT CREATE SESSION TO COURIER_ADMIN, COURIER_APP, COURIER_RO, COURIER_REP, COURIER_AUDIT;

-- 3. Przypisanie użytkowników do ról
GRANT role_admin TO COURIER_ADMIN;
GRANT role_app TO COURIER_APP;
GRANT role_ro TO COURIER_RO;
GRANT role_rep TO COURIER_REP;
GRANT role_audit TO COURIER_AUDIT;

-- Tabela: Cennik
CREATE TABLE Cennik (
    id_uslugi NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa_uslugi VARCHAR2(100) NOT NULL,
    cena_bazowa NUMBER(10, 2) NOT NULL,
    cena_za_kg NUMBER(10, 2)
);

-- Tabela: Faktury
CREATE TABLE Faktury (
    id_faktury NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numer_faktury VARCHAR2(50) NOT NULL UNIQUE,
    id_klienta NUMBER NOT NULL, -- Powiązanie z SQLSRV-HQ
    id_przesylki NUMBER,        -- Powiązanie z SQLSRV-HQ (przesyłka)
    kwota_netto NUMBER(10, 2) NOT NULL,
    kwota_vat NUMBER(10, 2) NOT NULL,
    kwota_brutto NUMBER(10, 2) NOT NULL,
    data_wystawienia DATE DEFAULT SYSDATE
);

-- Tabela: Platnosci
CREATE TABLE Platnosci (
    id_platnosci NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_faktury NUMBER NOT NULL,
    kwota NUMBER(10, 2) NOT NULL,
    data_platnosci DATE DEFAULT SYSDATE,
    metoda_platnosci VARCHAR2(30),
    CONSTRAINT fk_platnosc_faktura FOREIGN KEY (id_faktury) REFERENCES Faktury(id_faktury)
);

-- Tabela: RozliczeniaKurierskie
CREATE TABLE RozliczeniaKurierskie (
    id_rozliczenia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_kuriera NUMBER NOT NULL, -- Powiązanie z SQLSRV-HQ
    okres_rozliczeniowy VARCHAR2(7) NOT NULL,
    kwota_prowizji NUMBER(10, 2) NOT NULL,
    status_rozliczenia VARCHAR2(20) DEFAULT 'DO_REPOTU'
);

-- 4. Nadanie uprawnień do tabel
-- Dla administratora - pełny dostęp do wszystkich tabel
GRANT ALL PRIVILEGES ON Cennik TO role_admin;
GRANT ALL PRIVILEGES ON Faktury TO role_admin;
GRANT ALL PRIVILEGES ON Platnosci TO role_admin;
GRANT ALL PRIVILEGES ON RozliczeniaKurierskie TO role_admin;

-- Dla aplikacji - zapis i odczyt faktur oraz płatności
GRANT SELECT, INSERT, UPDATE ON Faktury TO role_app;
GRANT SELECT, INSERT, UPDATE ON Platnosci TO role_app;
GRANT SELECT ON Cennik TO role_app;

-- Dla SQL Server Linked Server (tylko odczyt)
GRANT SELECT ON Cennik TO role_ro;
GRANT SELECT ON Faktury TO role_ro;
GRANT SELECT ON Platnosci TO role_ro;
GRANT SELECT ON RozliczeniaKurierskie TO role_ro;

-- Dla replikacji
GRANT SELECT, INSERT, UPDATE, DELETE ON Cennik TO role_rep;
GRANT SELECT, INSERT, UPDATE, DELETE ON Faktury TO role_rep;
GRANT SELECT, INSERT, UPDATE, DELETE ON Platnosci TO role_rep;
GRANT SELECT, INSERT, UPDATE, DELETE ON RozliczeniaKurierskie TO role_rep;

-- Dla audytu (dostęp wyłącznie do widoków raportowych)

-- 5. Database Linki (Symulacja danych rozproszonych w Oracle)
-- Prywatny DB Link (używany przez COURIER_REP)
CREATE DATABASE LINK hq_link_private
   CONNECT TO COURIER_HQ_ADMIN IDENTIFIED BY "HQAdminPassword123!"
   USING 'SQLSRV-HQ';

-- Publiczny DB Link (do celów raportowych)
CREATE PUBLIC DATABASE LINK hq_link_public
   CONNECT TO COURIER_HQ_APP IDENTIFIED BY "HQAppPassword123!"
   USING 'SQLSRV-HQ';

-- 6. Widoki rozproszone
-- Zakładamy, że poprzez hq_link_public możemy odczytać tabele Klienci z SQLSRV-HQ
CREATE OR REPLACE VIEW vw_FakturyZKlientami AS
SELECT 
    f.id_faktury,
    f.numer_faktury,
    k.NazwaFirmy_ImieNazwisko AS nazwa_klienta,
    f.kwota_brutto,
    f.data_wystawienia
FROM Faktury f
JOIN Klienci@hq_link_public k ON f.id_klienta = k.IdKlienta;

-- Zestawienie faktur i statusów przesyłek (łączone z centralą)
CREATE OR REPLACE VIEW vw_FakturyStatusyPrzesylek AS
SELECT 
    f.id_faktury,
    f.numer_faktury,
    f.id_klienta,
    f.id_przesylki,
    f.kwota_brutto,
    f.data_wystawienia,
    p.StatusPrzesylki AS status_przesylki
FROM Faktury f
LEFT JOIN Przesylki@hq_link_public p ON f.id_przesylki = p.IdPrzesylki;

-- 7. Wyzwalacze INSTEAD OF do widoków rozproszonych
CREATE OR REPLACE TRIGGER trg_vw_FakturyZKlientami_Insert
INSTEAD OF INSERT ON vw_FakturyZKlientami
FOR EACH ROW
BEGIN
    -- Wyzwalacz pozwala na dodanie faktury dla istniejącego klienta z poziomu widoku
    INSERT INTO Faktury (numer_faktury, id_klienta, kwota_netto, kwota_vat, kwota_brutto, data_wystawienia)
    VALUES (
        :NEW.numer_faktury, 
        -- Wyszukanie IdKlienta na zdalnym serwerze na podstawie przekazanej nazwy
        (SELECT IdKlienta FROM Klienci@hq_link_public WHERE NazwaFirmy_ImieNazwisko = :NEW.nazwa_klienta),
        ROUND(:NEW.kwota_brutto / 1.23, 2), -- Symulowany podział kwoty
        ROUND(:NEW.kwota_brutto - (:NEW.kwota_brutto / 1.23), 2),
        :NEW.kwota_brutto,
        NVL(:NEW.data_wystawienia, SYSDATE)
    );
END;
/

-- Wyzwalacz INSTEAD OF INSERT do zestawienia faktur i statusów przesyłek
CREATE OR REPLACE TRIGGER trg_vw_FakturyStatusy_Insert
INSTEAD OF INSERT ON vw_FakturyStatusyPrzesylek
FOR EACH ROW
BEGIN
    INSERT INTO Faktury (numer_faktury, id_klienta, id_przesylki, kwota_netto, kwota_vat, kwota_brutto, data_wystawienia)
    VALUES (
        :NEW.numer_faktury,
        :NEW.id_klienta,
        :NEW.id_przesylki,
        ROUND(:NEW.kwota_brutto / 1.23, 2),
        ROUND(:NEW.kwota_brutto - (:NEW.kwota_brutto / 1.23), 2),
        :NEW.kwota_brutto,
        NVL(:NEW.data_wystawienia, SYSDATE)
    );
END;
/

-- Wyzwalacz INSTEAD OF UPDATE do zestawienia faktur i statusów przesyłek
CREATE OR REPLACE TRIGGER trg_vw_FakturyStatusy_Update
INSTEAD OF UPDATE ON vw_FakturyStatusyPrzesylek
FOR EACH ROW
BEGIN
    -- Modyfikacja danych finansowych lokalnie
    UPDATE Faktury
    SET 
        id_klienta = :NEW.id_klienta,
        id_przesylki = :NEW.id_przesylki,
        kwota_brutto = :NEW.kwota_brutto,
        kwota_netto = ROUND(:NEW.kwota_brutto / 1.23, 2),
        kwota_vat = ROUND(:NEW.kwota_brutto - (:NEW.kwota_brutto / 1.23), 2),
        data_wystawienia = :NEW.data_wystawienia
    WHERE id_faktury = :OLD.id_faktury;
    
    -- Aktualizacja statusu przesyłki na serwerze zdalnym, jeśli uległ zmianie
    IF :NEW.status_przesylki IS NOT NULL AND (:OLD.status_przesylki IS NULL OR :OLD.status_przesylki <> :NEW.status_przesylki) THEN
        UPDATE Przesylki@hq_link_public
        SET StatusPrzesylki = :NEW.status_przesylki
        WHERE IdPrzesylki = :NEW.id_przesylki;
    END IF;
END;
/

-- Nadanie uprawnień do widoków dla roli audytu
GRANT SELECT ON vw_FakturyZKlientami TO role_audit;
GRANT SELECT ON vw_FakturyStatusyPrzesylek TO role_audit;

-- 8. Procedury składowane (wystawianie faktur i rozliczenia)
CREATE OR REPLACE PROCEDURE usp_WystawFakture (
    p_id_klienta IN NUMBER,
    p_numer_faktury IN VARCHAR2,
    p_kwota_netto IN NUMBER,
    p_kwota_vat IN NUMBER,
    p_kwota_brutto IN NUMBER,
    p_id_przesylki IN NUMBER DEFAULT NULL
)
AS
BEGIN
    INSERT INTO Faktury (numer_faktury, id_klienta, id_przesylki, kwota_netto, kwota_vat, kwota_brutto)
    VALUES (p_numer_faktury, p_id_klienta, p_id_przesylki, p_kwota_netto, p_kwota_vat, p_kwota_brutto);
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'Błąd podczas wystawiania faktury: ' || SQLERRM);
END usp_WystawFakture;
/

CREATE OR REPLACE PROCEDURE usp_RozliczKuriera (
    p_id_kuriera IN NUMBER,
    p_okres IN VARCHAR2,
    p_kwota_prowizji IN NUMBER
)
AS
BEGIN
    INSERT INTO RozliczeniaKurierskie (id_kuriera, okres_rozliczeniowy, kwota_prowizji, status_rozliczenia)
    VALUES (p_id_kuriera, p_okres, p_kwota_prowizji, 'ZATWIERDZONE');
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Błąd podczas rozliczania kuriera: ' || SQLERRM);
END usp_RozliczKuriera;
/

