-- Oracle Cennik
-- 1. Tworzenie Ról
CREATE ROLE role_admin;
CREATE ROLE role_app;
CREATE ROLE role_ro;
CREATE ROLE role_rep;
CREATE ROLE role_audit;

-- 2. Tworzenie Użytkowników
CREATE USER COURIER_ADMIN IDENTIFIED BY AdminSecure123!;
CREATE USER COURIER_APP IDENTIFIED BY AppSecure123!;
CREATE USER COURIER_RO IDENTIFIED BY ROSecure123!;
CREATE USER COURIER_REP IDENTIFIED BY RepSecure123!;
CREATE USER COURIER_AUDIT IDENTIFIED BY AuditSecure123!;

-- Podstawowe uprawnienia do logowania
GRANT CREATE SESSION TO COURIER_ADMIN, COURIER_APP, COURIER_RO, COURIER_REP, COURIER_AUDIT;

-- 3. Przypisanie użytkowników do ról
GRANT role_admin TO COURIER_ADMIN;
GRANT role_app TO COURIER_APP;
GRANT role_ro TO COURIER_RO;
GRANT role_rep TO COURIER_REP;
GRANT role_audit TO COURIER_AUDIT;

-- Tabela: Cennik
CREATE TABLE Cennik (
    id_uslugi NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa_uslugi VARCHAR2(100) NOT NULL,
    cena_bazowa NUMBER(10, 2) NOT NULL
);

-- Tabela: Faktury
CREATE TABLE Faktury (
    id_faktury NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numer_faktury VARCHAR2(50) NOT NULL UNIQUE,
    id_klienta NUMBER NOT NULL, -- Powiązanie z SQLSRV-HQ
    kwota_netto NUMBER(10, 2) NOT NULL,
    kwota_vat NUMBER(10, 2) NOT NULL,
    kwota_brutto NUMBER(10, 2) NOT NULL,
    data_wystawienia DATE DEFAULT SYSDATE,
);

-- Tabela: Platnosci
CREATE TABLE Platnosci (
    id_platnosci NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_faktury NUMBER NOT NULL,
    kwota NUMBER(10, 2) NOT NULL,
    data_platnosci DATE DEFAULT SYSDATE,
    metoda_platnosci VARCHAR2(30),
    CONSTRAINT fk_platnosc_faktura FOREIGN KEY (id_faktury) REFERENCES Faktury(id_faktury)
);

-- Tabela: RozliczeniaKurierskie
CREATE TABLE RozliczeniaKurierskie (
    id_rozliczenia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_kuriera NUMBER NOT NULL, -- Powiązanie z SQLSRV-HQ
    okres_rozliczeniowy VARCHAR2(7) NOT NULL,
    kwota_prowizji NUMBER(10, 2) NOT NULL,
    status_rozliczenia VARCHAR2(20) DEFAULT 'DO_REPOTU'
);
